Repository Collusic/collusic-new, pull requests merged in 2022-11, with the labels that each got.

#242 Fix/240 : 회원가입 상황시 응답 바디에서 리프레시 토큰 제거
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
Labels: 🐛 bug

#245 feat/243 : 액세스 토큰 재발급 API
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TokenService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ReissuedTokenDto.java
Labels: 🐛 bug, ✨ feature, ♻️ refactor

#247 Fix/246 : CORS 문제 해결(토큰 재발급 필터 수정)
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationProvider.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/jwt/ExpiredTokenException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TokenService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
Labels: 🐛 bug, ♻️ refactor

#250 Feat/249 : 로그아웃 기능 추가 및 CORS 필터 추가
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CorsFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/CookieUtils.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
Labels: 🐛 bug, ✨ feature, ⚡️ 백엔드, ♻️ refactor

#252 fix/251 : 로그인 시 리프레시 토큰 쿠키에 담기
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
Labels: 🐛 bug, ⚡️ 백엔드

#254 fix : 로그아웃 기능 버그 해결
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
Labels: 🐛 bug, ⚡️ 백엔드

#255 Feat/248: 테스트 재설계에 따른 엔티티 수정 및 코드 수정 작업 완료
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Contribute.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Project.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/session/Session.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/state/State.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Measure.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TrackService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateRequestDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackUpdateRequestDto.java
  server/collusic-be/src/main/resources/import.sql
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/TrackAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
Labels: ✨ feature, ⚡️ 백엔드
