Repository Collusic/collusic-new, pull requests merged in 2022-01, with the labels that each got.

#18 Feat/be/Issue-16
  .gitignore
  .idea/.gitignore
  .idea/collusic-new.iml
  .idea/dbnavigator.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  server/collusic-be/.gitignore
  server/collusic-be/.mvn/wrapper/MavenWrapperDownloader.java
  server/collusic-be/.mvn/wrapper/maven-wrapper.jar
  server/collusic-be/.mvn/wrapper/maven-wrapper.properties
  server/collusic-be/mvnw
  server/collusic-be/mvnw.cmd
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/CollusicBeApplication.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/Field.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/FieldEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/genre/Genre.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/genre/GenreEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/mood/Mood.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/mood/MoodEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/upload/UploadFile.java
  server/collusic-be/src/main/resources/application.properties
  server/collusic-be/src/test/java/com/collusic/collusicbe/CollusicBeApplicationTests.java
Labels: 👨🏻‍💻백엔드

#22 [Refactor] Feat/be/issue 16
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/Field.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/FieldEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/genre/Genre.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/genre/GenreEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/mood/Mood.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/mood/MoodEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
Labels: 👨🏻‍💻백엔드

#23 [Refactor] Feat/be/Issue-16
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/upload/UploadFile.java
Labels: 👨🏻‍💻백엔드, Refactor

#29 Feat/be/Issue-3
  server/collusic-be/.gitignore
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/BaseTimeEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/FieldEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/genre/GenreEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/mood/MoodEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectSaveRequestDto.java
  server/collusic-be/src/main/resources/application.properties
Labels: 👨🏻‍💻백엔드

#30 [Fix] Feat/be/Issue-3
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectSaveRequestDto.java
  server/collusic-be/src/main/resources/application.properties
Labels: 👨🏻‍💻백엔드

#31 [Fix] Feat/be/Issue-3
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
Labels: 👨🏻‍💻백엔드

#42 Feat/be/Issue-34
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectsWithPaginationDto.java
  server/collusic-be/src/main/resources/application.properties
Labels: 👨🏻‍💻백엔드

#44 Feat/be/Issue-43
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
Labels: 👨🏻‍💻백엔드

#55 Feat/be/Issue-45
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/StringUtils.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectUpdateRequestDto.java
  server/collusic-be/src/main/resources/application.properties
Labels: 👨🏻‍💻백엔드

#58 Feat/be/Issue-57
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
Labels: 👨🏻‍💻백엔드

#64 Feat/be/Issue-63
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/ContributeProjectFieldEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/field/RequestProjectFieldEntity.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/requestproject/RequestProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ContributeProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ContributeProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/ContributeProjectResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/ContributeProjectSaveRequestDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectSaveRequestDto.java
Labels: 👨🏻‍💻백엔드

#67 Feat/be/Issue-66
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectResponseDto.java
Labels: 👨🏻‍💻백엔드, Refactor

#70 feat : 요청작 삭제 API 수정
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
Labels: 👨🏻‍💻백엔드

#71 Feat/be/Issue-69
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ContributeProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ContributeProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/ContributeProjectUpdateRequestDto.java
Labels: 👨🏻‍💻백엔드

#73 Feat/be/Issue-72
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProject.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ContributeProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ContributeProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectResponseDto.java
Labels: 👨🏻‍💻백엔드

#76 Feat/be/Issue-74
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ContributeProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ContributeProjectApiController.java
Labels: 👨🏻‍💻백엔드

#65 Feat/fe/issue 47
  client/src/view/CreateRequestPage.scss
  client/src/view/CreateRequestPageView.tsx
  client/src/view/CreateTitle.scss
  client/src/view/CreateTitleView.tsx
  client/src/viewmodel/CreateRequestViewModel.tsx
Labels: enhancement, 💻프론트엔드

#86 [Refactor] 메인페이지 요청작 페이지네이션 기능 정렬 기준 정의
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
Labels: 👨🏻‍💻백엔드

#101 Feat/fe/issue 48
  client/src/utils/style/MainPage.scss
  client/src/view/CreateContent.scss
  client/src/view/CreateContentView.tsx
  client/src/view/NavBar.scss
  client/src/viewmodel/CreateRequestViewModel.tsx
Labels: enhancement, 💻프론트엔드

#103 Feat/fe/issue 50
  client/src/view/CreateMelody.scss
  client/src/view/CreateMelodyView.tsx
  client/src/view/CreateRequestPage.scss
  client/src/viewmodel/CreateRequestViewModel.tsx
Labels: enhancement, 💻프론트엔드

#113 Feat/be/Issue-112
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ContributeProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ContributeProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/ContributeProjectResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/dto/RequestProjectDetailPageDto.java
Labels: 👨🏻‍💻백엔드, Refactor
