Repository Collusic/collusic-new, pull requests merged in 2022-12, with the labels that each got.

#258 feat/179: 회원가입/로그인 JWT 토큰 발급 api 요청 구현 완료
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/blocks/NavBar/index.tsx
  client/src/mocks/handlers/user.ts
  client/src/model/signInModel.ts
  client/src/utils/axios.ts
  client/src/viewmodel/AuthVerify.tsx
  client/src/viewmodel/RedirectViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#257 feat/256 : 프로젝트 생성 및 목록 보기 API 개발
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/LikeRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Project.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectLike.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectInventoryResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectsResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/LikeResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProjectCreateRequestDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProjectCreateResponseDto.java
  server/collusic-be/src/main/resources/application.yml
  server/collusic-be/src/main/resources/import.sql
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/ProjectAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/ProjectServiceTest.java
Labels: ✨ feature, ⚡️ 백엔드, ✅ test

#261 feat/236: 프로젝트 설정 컴포넌트 구현 완료
  client/package-lock.json
  client/package.json
  client/public/assets/logo/logo.png
  client/public/assets/logo/logo@2x.png
  client/public/assets/logo/logo@3x.png
  client/public/index.html
  client/src/App.tsx
  client/src/api/axios.ts
  client/src/api/project.ts
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.scss
  client/src/components/atoms/Toggle/index.tsx
  client/src/components/blocks/Bpm/index.tsx
  client/src/components/blocks/Bpm/style.scss
  client/src/components/blocks/NavBar/index.tsx
  client/src/components/blocks/NavBar/style.scss
  client/src/components/blocks/ProjectSetting/index.tsx
  client/src/components/blocks/ProjectSetting/style.scss
  client/src/components/blocks/RecordDevice/index.tsx
  client/src/components/blocks/RecordDevice/style.scss
  client/src/components/blocks/SessionMelody/index.tsx
  client/src/components/blocks/SessionMelody/style.scss
  client/src/components/blocks/TrackTag/index.tsx
  client/src/components/blocks/TrackTag/style.scss
  client/src/components/pages/CreateProject/index.jsx
  client/src/components/pages/CreateProject/style.scss
  client/src/index.tsx
  client/src/model/detailRequestProjectModel.ts
  client/src/model/projectModel.ts
  client/src/model/requestProjectsModel.ts
  client/src/stories/Bpm.stories.tsx
  client/src/stories/ProjectSetting.stories.tsx
  client/src/stories/RecordDevice.stories.tsx
  client/src/stories/TrackTag.stories.tsx
  client/src/types/projectType.ts
  client/src/utils/data/track.ts
  client/src/utils/slider.ts
  client/src/utils/style/index.scss
  client/src/viewmodel/AuthVerify.tsx
  client/src/viewmodel/CreateContributeViewModel.tsx
  client/src/viewmodel/CreateRequestViewModel.tsx
  client/src/viewmodel/ProjectViewModel.tsx
  client/src/viewmodel/RedirectViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#268 Feat/260: 트랙 생성 시 오디오 파일 업로드 기능 구현 완료
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TrackService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/UnknownMemberException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TrackController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProjectCreateRequestDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateRequestDto.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/AbstractAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/ProjectAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/TrackAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/ProjectServiceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
  server/collusic-be/src/test/resources/assets/schoolbell.mp3
Labels: ✨ feature, ⚡️ 백엔드

#312 Feat/274 : 프로젝트 도메인 테스트 커버리지 높이기
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/project/ProjectServiceTest.java
Labels: ⚡️ 백엔드, ✅ test

#313 feat/262: 프로젝트 목록 컴포넌트 뷰 구현
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/public/assets/banner/banner.png
  client/public/assets/likeIcon/like.png
  client/public/assets/likeIcon/unlike.png
  client/public/assets/plus/plus.png
  client/public/assets/preview/pause.png
  client/public/assets/preview/play.png
  client/public/assets/trackIcon/acousticguitar.png
  client/public/assets/trackIcon/crap.png
  client/public/assets/trackIcon/drum.png
  client/public/assets/trackIcon/electricguitar.png
  client/public/assets/trackIcon/etc.png
  client/public/assets/trackIcon/maracas.png
  client/public/assets/trackIcon/piano.png
  client/public/assets/trackIcon/recorder.png
  client/public/assets/trackIcon/violin.png
  client/public/assets/trackIcon/vocal.png
  client/public/index.html
  client/src/App.tsx
  client/src/api/project.ts
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/LikeButton/index.tsx
  client/src/components/atoms/LikeButton/style.scss
  client/src/components/atoms/PreviewButton/index.tsx
  client/src/components/atoms/PreviewButton/style.scss
  client/src/components/atoms/TrackIcon/index.tsx
  client/src/components/atoms/TrackIcon/style.scss
  client/src/components/blocks/ProjectItem/index.tsx
  client/src/components/blocks/ProjectItem/style.scss
  client/src/components/blocks/ProjectList/index.tsx
  client/src/components/blocks/ProjectList/style.scss
  client/src/components/blocks/TrackTag/index.tsx
  client/src/components/pages/CreateProject/index.jsx
  client/src/components/pages/CreateProjectPage/index.jsx
  client/src/components/pages/CreateProjectPage/style.scss
  client/src/components/pages/ProjectListPage/index.tsx
  client/src/components/pages/ProjectListPage/style.scss
  client/src/model/projectModel.ts
  client/src/stories/LikeButton.stories.tsx
  client/src/stories/PreviewButton.stories.tsx
  client/src/stories/ProjectItem.stories.tsx
  client/src/stories/ProjectList.stories.tsx
  client/src/stories/TrackIcon.stories.tsx
  client/src/types/projectType.ts
  client/src/utils/data/track.ts
  client/src/view/StartPageView.tsx
  client/src/viewmodel/ProjectListViewModel.tsx
  client/src/viewmodel/ProjectSettingViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#318 Chore/317: 미디어 파일 url 더미데이터에 추가 완료
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
  server/collusic-be/src/main/resources/import.sql
Labels: ⚡️ 백엔드, ✅ test, 📦 chore

#322 Fix/321 : 새로 등록된 도메인 Origin 등록 및 SSL 인증서 발급을 위한 설정 추가
  server/collusic-be/certbot/etc/accounts/acme-v02.api.letsencrypt.org/directory/9b8e105bbe7e72cefeba137d1b2c4b08/meta.json
  server/collusic-be/certbot/etc/accounts/acme-v02.api.letsencrypt.org/directory/9b8e105bbe7e72cefeba137d1b2c4b08/private_key.json
  server/collusic-be/certbot/etc/accounts/acme-v02.api.letsencrypt.org/directory/9b8e105bbe7e72cefeba137d1b2c4b08/regr.json
  server/collusic-be/certbot/etc/csr/0000_csr-certbot.pem
  server/collusic-be/certbot/etc/csr/0001_csr-certbot.pem
  server/collusic-be/certbot/etc/keys/0000_key-certbot.pem
  server/collusic-be/certbot/etc/keys/0001_key-certbot.pem
  server/collusic-be/docker-compose.yml
  server/collusic-be/nginx/conf.d/default.conf
  server/collusic-be/nginx/log/access.log
  server/collusic-be/nginx/log/error.log
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
Labels: 🐛 bug, ⚡️ 백엔드

#324 Fix/323: 미리듣기 클릭 및 좋아요 클릭 시 바로 상세페이지로 이동하는 현상 해결
  client/src/App.tsx
  client/src/components/atoms/LikeButton/index.tsx
  client/src/components/atoms/PreviewButton/index.tsx
  client/src/components/blocks/ProjectItem/style.scss
  client/src/types/projectType.ts
  client/src/viewmodel/AuthVerify.tsx
  client/src/viewmodel/ProjectItemViewModel.tsx
Labels: 🐛 bug, 📚 프론트엔드

#325 Feat/282: 상세페이지 Bpm 컴포넌트 구현
  client/src/components/atoms/Bpm/index.tsx
  client/src/components/atoms/Bpm/style.scss
  client/src/components/blocks/BpmBar/index.tsx
  client/src/components/blocks/BpmBar/style.scss
  client/src/components/blocks/ProjectSetting/index.tsx
  client/src/stories/Bpm.stories.tsx
  client/src/stories/BpmBar.stories.tsx
Labels: ✨ feature, 📚 프론트엔드

#326 Feat/280: 상세페이지 프로젝트 제목 컴포넌트 구현
  client/src/components/atoms/DetailTitle/index.tsx
  client/src/components/atoms/DetailTitle/style.scss
  client/src/stories/DetailTitle.stories.tsx
Labels: ✨ feature, 📚 프론트엔드

#327 Fix/321 : HTTPS 적용하기
  server/collusic-be/docker-compose.yml
Labels: 🐛 bug, ⚡️ 백엔드

#328 Feat/281: 좋아요 버튼 구현
  client/src/components/atoms/LikeButton/index.tsx
  client/src/components/atoms/LikeButton/style.scss
  client/src/stories/LikeButton.stories.tsx
Labels: ✨ feature, 📚 프론트엔드
