Repository Collusic/collusic-new, pull requests merged in 2022-08, with the labels that each got.

#180 feat/172 구글 Oauth 로그인/회원가입 기능 구현 완료
  client/.gitignore
  client/src/App.tsx
  client/src/components/Modal.tsx
  client/src/mocks/handlers/user.ts
  client/src/model/userModel.ts
  client/src/utils/axios.ts
  client/src/view/ProjectListView.tsx
  client/src/view/SignInView.tsx
  client/src/viewmodel/RedirectViewModel.tsx
  client/src/viewmodel/SignInViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#182 feat/167 : 회원가입 / 로그인 로직 Validation 및 Exception Handling
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/DuplicatedNicknameException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ExceptionDetailResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ExceptionInfoResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ExceptionResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/advice/ExceptionControllerAdvice.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
Labels: ✨ feature, ⚡️ 백엔드

#184 refactor/183 : 응답 애트리뷰트에 대한 카멜케이스 적용
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
Labels: ⚡️ 백엔드, ♻️ refactor

#185 refactor/181 : application.properties -> yml로 전환 및 암호화 작업 완료
  server/collusic-be/.gitignore
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/CollusicBeApplication.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/JasyptConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/GoogleClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/KakaoClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/NaverClientService.java
  server/collusic-be/src/main/resources/application-dev_oauth.yml
  server/collusic-be/src/main/resources/application-dev_redis.yml
  server/collusic-be/src/main/resources/application-local_oauth.yml
  server/collusic-be/src/main/resources/application-local_redis.yml
  server/collusic-be/src/main/resources/application.properties
  server/collusic-be/src/main/resources/application.yml
  server/collusic-be/src/test/java/com/collusic/collusicbe/config/JasyptTest.java
Labels: ⚡️ 백엔드, ♻️ refactor, ⚙️ setting

#187 Bug/186: CORS 이슈 해결
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
Labels: 🐛 bug, ⚡️ 백엔드

#194 feat/188 : s3 및 cloudfront 적용 완료
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/S3Config.java
  server/collusic-be/src/main/resources/application-aws.yml
Labels: ✨ feature, ⚡️ 백엔드

#191 feat/190: 회원가입 시 닉네임 유효성 검사 작업 완료
  .gitignore
  client/src/App.tsx
  client/src/utils/axios.ts
  client/src/utils/validation.tsx
  client/src/viewmodel/RedirectViewModel.tsx
  client/src/viewmodel/SignInViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#200 Refactor/199 : 리프레시 토큰 응답 방식 개선하기
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TokenService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
Labels: ⚡️ 백엔드, ♻️ refactor
