Repository Collusic/collusic-new, pull requests merged in 2022-09, with the labels that each got.

#198 Refactor/197 : 닉네임 중복 체크 기능 응답 구조 수정
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/NicknameValidationResponseDto.java
Labels: ⚡️ 백엔드, ♻️ refactor

#204 Fix/203 : 닉네임 사이즈 검증 예외 메시지 수정
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
Labels: 🐛 bug, ⚡️ 백엔드

#195 feat/189 : 사용자 프로필 이미지 업로드 api 구현 완료
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Member.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/ProfileContentType.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
Labels: ✨ feature, ⚡️ 백엔드

#205 feat/196: 공통 컴포넌트 및 스타일 구현완료
  client/.eslintignore
  client/.storybook/index.css
  client/.storybook/preview-head.html
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/public/assets/locker/locked.svg
  client/public/assets/locker/unlocked.svg
  client/public/assets/mike/mike.svg
  client/public/index.html
  client/src/components/Button.tsx
  client/src/components/RecordButton.tsx
  client/src/components/Toggle.tsx
  client/src/model/projectModel.ts
  client/src/stories/Button.stories.tsx
  client/src/stories/LineButton.stories.tsx
  client/src/stories/RecordButton.stories.tsx
  client/src/stories/TextButton.stories.tsx
  client/src/stories/Toggle.stories.tsx
  client/src/utils/style/_color.scss
  client/src/utils/style/button.scss
  client/src/utils/style/recordButton.scss
  client/src/utils/style/toggle.scss
  client/tsconfig.json
Labels: ✨ feature, 📚 프론트엔드

#209 [Refactor/208]: 프로필 이미지 업로드 api 변경사항 반영
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProfileUploadResponseDto.java
Labels: 🧱 infra, ⚡️ 백엔드, ♻️ refactor

#214 feature/206: 입력장치 컴포넌트 구현 완료
  client/public/assets/arrow/arrow_down.zip
  client/public/assets/arrow/arrow_up.svg
  client/public/assets/arrow_down/arrow_down.png
  client/public/assets/arrow_down/arrow_drop_up_black_24dp@2x.png
  client/public/assets/arrow_down/arrow_drop_up_black_24dp@3x.png
  client/src/components/RecordDevice.tsx
  client/src/stories/RecordDevice.stories.tsx
  client/src/utils/style/recordDevice.scss
Labels: ✨ feature, 📚 프론트엔드

#219 refactor/218 디렉토리 구조 변경 완료
  client/src/App.tsx
  client/src/components/Pause.tsx
  client/src/components/Play.tsx
  client/src/components/atoms/Audio/index.tsx
  client/src/components/atoms/Audio/style.scss
  client/src/components/atoms/Bar/index.tsx
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.scss
  client/src/components/atoms/LoginButton/index.tsx
  client/src/components/atoms/LoginButton/style.scss
  client/src/components/atoms/Modal/index.tsx
  client/src/components/atoms/Modal/style.scss
  client/src/components/atoms/PauseButton/index.tsx
  client/src/components/atoms/PlayButton/index.tsx
  client/src/components/atoms/RecordButton/index.tsx
  client/src/components/atoms/RecordButton/style.scss
  client/src/components/atoms/Toggle/index.tsx
  client/src/components/atoms/Toggle/style.scss
  client/src/components/blocks/AudioPlayer/index.tsx
  client/src/components/blocks/NavBar/index.tsx
  client/src/components/blocks/NavBar/style.scss
  client/src/components/blocks/RecordDevice/index.tsx
  client/src/components/blocks/RecordDevice/style.scss
  client/src/components/blocks/SignIn/index.tsx
  client/src/components/blocks/SignIn/style.scss
  client/src/components/blocks/SignUp/index.tsx
  client/src/components/blocks/SignUp/style.scss
  client/src/stories/Button.stories.tsx
  client/src/stories/LineButton.stories.tsx
  client/src/stories/LoginButton.stories.tsx
  client/src/stories/RecordButton.stories.tsx
  client/src/stories/RecordDevice.stories.tsx
  client/src/stories/TextButton.stories.tsx
  client/src/stories/Toggle.stories.tsx
  client/src/utils/requestStates.tsx
  client/src/view/DetailRequestView.tsx
  client/src/view/RequestProjectView.tsx
  client/src/viewmodel/SignInViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: 📚 프론트엔드, ♻️ refactor

#217 feature/215: 세션 마디 컴포넌트 구현 완료
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.scss
  client/src/components/atoms/Span/index.tsx
  client/src/components/atoms/Span/style.scss
  client/src/components/blocks/SessionMelody/index.tsx
  client/src/components/blocks/SessionMelody/style.scss
  client/src/model/projectModel.ts
  client/src/stories/Button.stories.tsx
  client/src/stories/LineButton.stories.tsx
  client/src/stories/SessionMelody.stories.tsx
  client/src/stories/Span.stories.tsx
  client/src/stories/TextButton.stories.tsx
  client/src/types/projectType.ts
Labels: ✨ feature, 📚 프론트엔드
