Repository Collusic/collusic-new, pull requests merged in 2022-07, with the labels that each got.

#138 feature/130: 로그인 및 회원가입 모달 구현 완료
  client/public/assets/signin/modal.png
  client/public/assets/signin/modal@2x.png
  client/public/assets/signin/modal@3x.png
  client/src/App.tsx
  client/src/index.tsx
  client/src/model/signInModel.ts
  client/src/utils/style/SignIn.scss
  client/src/utils/style/StartPage.scss
  client/src/utils/style/_color.scss
  client/src/utils/style/index.scss
  client/src/view/NavBarView.tsx
  client/src/view/SignInView.tsx
  client/src/view/StartPageView.tsx
Labels: ✨ feature, 📚 프론트엔드

#137 feature/131: 로그인 및 회원가입 버튼 컴포넌트 구현 완료
  client/public/assets/login/google.svg
  client/public/assets/login/kakao.svg
  client/public/assets/login/naver.svg
  client/src/App.tsx
  client/src/components/LoginButton.tsx
  client/src/utils/style/login.scss
  client/src/utils/style/loginButton.scss
  client/src/view/LoginView.tsx
Labels: ✨ feature, 📚 프론트엔드

#145 chore/139: storybook, eslint, prettier 보일러플레이팅 완료
  client/.eslintrc.js
  client/.prettierrc
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/stories/LoginButton.stories.tsx
Labels: 📚 프론트엔드, 📦 chore

#146 feat/142 - JWT Util 클래스 구현
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/util/JWTUtilTest.java
Labels: ✨ feature, ⚡️ 백엔드, ✅ test

#150 feat/be/143 : 회원가입 / 로그인 기능 구현
  server/collusic-be/.gitignore
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CannotSignUpException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CustomOAuth2UserService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTGenerateFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/OAuthAttributes.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/dto/OAuthInfoResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Member.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRole.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Role.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/SnsType.java
  server/collusic-be/src/main/resources/application.properties
Labels: ✨ feature, ⚡️ 백엔드

#153 refactor/151 : OAuth 플로우 구조 개선
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/CollusicBeApplication.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2ClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseType.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2ProviderClientManager.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Response.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/GoogleAccessTokenClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/GoogleClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/GoogleProfileClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/dto/GoogleProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/dto/GoogleTokenResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/KakaoAccessTokenClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/KakaoClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/KakaoProfileClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/dto/KakaoProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/dto/KakaoTokenResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/NaverAccessTokenClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/NaverClientService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/NaverProfileClient.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/dto/NaverProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/dto/NaverTokenResponse.java
Labels: ⚡️ 백엔드, ♻️ refactor

#161 feat/155 : JWT 검증 및 인가 기능 구현 완료
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CustomOAuth2UserService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationProvider.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationToken.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTGenerateFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTVerifyResult.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/OAuthAttributes.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/dto/OAuthInfoResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/util/JWTUtilTest.java
Labels: ✨ feature, ⚡️ 백엔드

#152 feat/147: 모달 컴포넌트 닫기 기능 구현 완료
  client/public/assets/close/close_black_24dp.png
  client/public/assets/close/close_black_24dp@2x.png
  client/public/assets/close/close_black_24dp@3x.png
  client/src/App.tsx
  client/src/components/LoginButton.tsx
  client/src/index.tsx
  client/src/utils/style/SignIn.scss
  client/src/view/LoginView.tsx
  client/src/view/NavBarView.tsx
  client/src/view/SignInView.tsx
  client/src/view/StartPageView.tsx
Labels: ✨ feature, 📚 프론트엔드

#162 feat/148: 로그인/회원가입 모달창 구현 완료
  client/package-lock.json
  client/public/assets/signin/logo@2x.png
  client/src/stories/LoginButton.stories.tsx
  client/src/utils/style/Modal.scss
  client/src/utils/style/loginButton.scss
  client/src/view/ModalView.tsx
  client/src/view/SignInView.tsx
  client/src/view/StartPageView.tsx
Labels: ✨ feature, 📚 프론트엔드

#165 bug/164: 회원가입/로그인 모달창 css 수정 완료
  client/src/utils/style/Modal.scss
  client/src/view/ModalView.tsx
Labels: 🐛 bug, 📚 프론트엔드

#171 faet/158: Swagger 적용 완료
  server/collusic-be/pom.xml
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SwaggerConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
  server/collusic-be/src/main/resources/application.properties
Labels: ✨ feature, ⚡️ 백엔드

#175 chore/174: MSW 보일러플레이팅
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/index.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers/user.ts
  client/src/mocks/index.ts
Labels: 📚 프론트엔드, 📦 chore

#173 feat/168 - 닉네임 중복 검사 API 구현
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/NicknameValidationResponseDto.java
Labels: ✨ feature, ⚡️ 백엔드

#178 feat/169 : OAuth2 리소스 서버로부터 profile url 추가로 받아오는 기능 구현
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/dto/GoogleProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/dto/KakaoProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/dto/NaverProfileResponse.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
Labels: ✨ feature, ⚡️ 백엔드

#177 feat/163: 회원가입/로그인 추가 정보 입력 모달창 구현 완료
  .gitignore
  client/.eslintrc.js
  client/public/assets/signin/default_profile.png
  client/public/assets/signin/default_profile@2x.png
  client/public/assets/signin/default_profile@3x.png
  client/public/assets/signin/info_black_24dp.svg
  client/src/App.tsx
  client/src/components/LoginButton.tsx
  client/src/components/Modal.tsx
  client/src/model/signUpModel.ts
  client/src/utils/style/Modal.scss
  client/src/utils/style/NavBar.scss
  client/src/utils/style/SignUp.scss
  client/src/utils/style/StartPage.scss
  client/src/utils/style/index.scss
  client/src/view/NavBarView.tsx
  client/src/view/SignInView.tsx
  client/src/view/SignUpView.tsx
  client/src/view/StartPageView.tsx
  client/src/viewmodel/SignInViewModel.tsx
  client/src/viewmodel/SignUpViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드
