Repository Collusic/collusic-new, pull requests merged in 2022-10, with the labels that each got.

#225 bug/224: 디렉토리 구조 변경 후 경로 에러 해결 완료
  client/src/components/blocks/Audio/index.tsx
  client/src/components/blocks/Audio/style.scss
  client/src/components/blocks/NavBar/index.tsx
  client/src/model/detailRequestProjectModel.ts
  client/src/types/userType.ts
  client/src/utils/requestStates.tsx
  client/src/view/DetailRequestView.tsx
  client/src/view/RequestProjectView.tsx
Labels: 🐛 bug, 📚 프론트엔드

#227 feat/226 : 어노테이션 기반 개선하기
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/WebConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/LoginMember.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/LoginMemberArgumentResolver.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ParameterEmptyException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
Labels: ✨ feature, ⚡️ 백엔드

#222 feature/221: BPM 컴포넌트 구현 완료
  client/.eslintrc.js
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/LoginButton/index.tsx
  client/src/components/atoms/RecordButton/index.tsx
  client/src/components/atoms/Toggle/index.tsx
  client/src/components/blocks/Bpm/index.tsx
  client/src/components/blocks/Bpm/style.scss
  client/src/components/blocks/RecordDevice/index.tsx
  client/src/components/blocks/SessionMelody/index.tsx
  client/src/stories/Bpm.stories.tsx
  client/src/stories/RecordButton.stories.tsx
  client/src/stories/RecordDevice.stories.tsx
  client/src/utils/slider.ts
  client/src/viewmodel/ProjectViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#230 Feat/229: 트랙 CRUD API 구현 완료
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JwtAuthenticationEntryPoint.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Member.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Project.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Measure.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/TrackRepository.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/TrackTag.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ForbiddenException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/UnAuthorizedException.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/advice/ExceptionControllerAdvice.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/service/TrackService.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TrackController.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProjectResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateRequestDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateResponseDto.java
  server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackUpdateRequestDto.java
  server/collusic-be/src/main/resources/application.yml
  server/collusic-be/src/main/resources/import.sql
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/AbstractAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/TrackAcceptanceTest.java
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
Labels: ✨ feature, ⚡️ 백엔드

#233 Fix/232: 애플리케이션 빌드 시 트랙 관련 테스트 실패하는 이슈 해결
  server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
Labels: 🐛 bug, ⚡️ 백엔드, ✅ test

#235 feature/223: 트랙 태그 컴포넌트 구현 완료
  client/.storybook/main.js
  client/package.json
  client/public/assets/track/selected/acousticguitar.svg
  client/public/assets/track/selected/crap.svg
  client/public/assets/track/selected/drum.svg
  client/public/assets/track/selected/electricguitar.svg
  client/public/assets/track/selected/maracas.svg
  client/public/assets/track/selected/piano.svg
  client/public/assets/track/selected/recorder.svg
  client/public/assets/track/selected/violin.svg
  client/public/assets/track/selected/vocal.svg
  client/public/assets/track/unselected/acousticguitar.svg
  client/public/assets/track/unselected/crap.svg
  client/public/assets/track/unselected/drum.svg
  client/public/assets/track/unselected/electricguitar.svg
  client/public/assets/track/unselected/maracas.svg
  client/public/assets/track/unselected/piano.svg
  client/public/assets/track/unselected/recorder.svg
  client/public/assets/track/unselected/violin.svg
  client/public/assets/track/unselected/vocal.svg
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.scss
  client/src/components/blocks/SessionMelody/style.scss
  client/src/components/blocks/TrackTag/index.tsx
  client/src/components/blocks/TrackTag/style.scss
  client/src/model/projectModel.ts
  client/src/stories/TrackTag.stories.tsx
  client/src/types/projectType.ts
  client/src/utils/data/trackSrc.ts
Labels: ✨ feature, 📚 프론트엔드

#238 Fix/237: handle 함수 props 이름 변경 완료
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/LoginButton/index.tsx
  client/src/components/blocks/SignIn/index.tsx
  client/src/components/blocks/TrackTag/index.tsx
  client/src/stories/TrackTag.stories.tsx
  client/src/viewmodel/SignInViewModel.tsx
Labels: 🐛 bug, 📚 프론트엔드

#234 Feat/231: 배포 및 테스트 서버를 위한 도커 설정 완료
  server/collusic-be/Dockerfile-dev
  server/collusic-be/docker-compose.yml
  server/collusic-be/run_script.sh
Labels: 🧱 infra, ⚡️ 백엔드, ⚙️ setting
