Repository Collusic/collusic-new, pull requests merged in 2024-01, with the labels that each got.

#394 feat/389: 현재 사용 중인 입력장치 노출
  client/src/components/blocks/RecordDevice/index.tsx
  client/src/hooks/useInputDevice.ts
Labels: 📚 프론트엔드, 😤qa

#397 Fix/391 : [QA] [로그인] 로그인이 간헐적으로 풀리는 현상
  client/src/components/atoms/Auth/hooks/useAuth.ts
  client/src/model/authModel.ts
  client/src/viewmodel/ProjectItemViewModel.tsx
Labels: 🐛 bug, 📚 프론트엔드, 😤qa

#396 Fix/395: [QA] 입력장치 열었을 때 프로젝트 세팅 박스 레이아웃이 깨지는 현상 해결
  client/src/components/blocks/BpmBar/style.scss
  client/src/components/blocks/RecordDevice/style.scss
Labels: 🐛 bug, 📚 프론트엔드, 😤qa

#402 Feat/388 : [FE] [녹음] 녹음 시작할 때 재생바 이동
  client/src/components/blocks/TrackPlayer/index.tsx
  client/src/constants/audio.ts
  client/src/hooks/useAudios.ts
  client/src/hooks/useTime.ts
  client/src/hooks/useTrackPlayer.ts
  client/src/hooks/useTrackTimer.ts
  client/src/model/audioModel.ts
  client/src/utils/throttle.ts
  client/src/viewmodel/UnderPlayBarViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#405 feat/401 : statusCode가 401일 때, 메인 페이지 리다이렉션 및 로그인 모달 노출 구현
  client/src/api/axios.ts
  client/src/components/atoms/Auth/AuthRequired.tsx
  client/src/viewmodel/RouteHandlerViewModel.tsx
Labels: 📚 프론트엔드, 😤qa

#407 Feat/403: [FE] [녹음] 녹음 시 트랙 재생 관련 인터랙션 막기
  client/src/components/atoms/TrackPlayBox/index.tsx
  client/src/components/atoms/TrackRecordBox/index.tsx
  client/src/components/atoms/TrackRecordBox/style.scss
  client/src/components/blocks/TrackPlayer/index.tsx
  client/src/components/blocks/TrackSetting/index.tsx
  client/src/hooks/useCreateTrack.ts
  client/src/hooks/useTrackPlayer.ts
  client/src/viewmodel/UnderPlayBarViewModel.tsx
Labels: ✨ feature, 📚 프론트엔드

#412 Fix/411: [FE] [프로젝트 생성] 프로젝트 생성 api 요청에 오디오 파일 추가
  client/src/api/axios.ts
  client/src/api/project.ts
  client/src/components/atoms/TrackPlayBox/index.tsx
  client/src/components/blocks/ProjectSetting/index.tsx
  client/src/components/blocks/TrackPlayer/index.tsx
  client/src/constants/key.ts
  client/src/hooks/useAudios.ts
  client/src/types/audioType.ts
  client/src/utils/audio.ts
  client/src/viewmodel/CreateProjectViewModel.tsx
Labels: 🐛 bug, ✨ feature, 📚 프론트엔드
